// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCoBU5_SJ6Bm7VaCcW0nCp46pVZGwv1u0',
    appId: '1:1010798285867:web:bb9b173339bcd700dcc66e',
    messagingSenderId: '1010798285867',
    projectId: 'sembako-store',
    authDomain: 'sembako-store.firebaseapp.com',
    storageBucket: 'sembako-store.firebasestorage.app',
    measurementId: 'G-2BTRHM90C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TNH_PPpzLZ2aNMKwqvV2TioFJMPCvgE',
    appId: '1:1010798285867:android:7314399e9ded95e2dcc66e',
    messagingSenderId: '1010798285867',
    projectId: 'sembako-store',
    storageBucket: 'sembako-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBocStbEZHyaKjD-apF4B89CGIZ6OGV1Cg',
    appId: '1:1010798285867:ios:5ec42399732a2ea0dcc66e',
    messagingSenderId: '1010798285867',
    projectId: 'sembako-store',
    storageBucket: 'sembako-store.firebasestorage.app',
    iosBundleId: 'com.example.projectUasEcomerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCoBU5_SJ6Bm7VaCcW0nCp46pVZGwv1u0',
    appId: '1:1010798285867:web:2e362bc62d962331dcc66e',
    messagingSenderId: '1010798285867',
    projectId: 'sembako-store',
    authDomain: 'sembako-store.firebaseapp.com',
    storageBucket: 'sembako-store.firebasestorage.app',
    measurementId: 'G-WG66XTEWEB',
  );
}
